version: '3'

services:
  nodejs:
    build:
      context: node
      dockerfile: Dockerfile
    image: gustcoder/nodejs
    container_name: nodejs
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s
    command: bash -c "npm install && node index.js"
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./node:/usr/src/app
    networks:
      - node-network
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network      

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    image: gustcoder/nginx
    container_name: nginx
    ports:
      - "8080:80"
    tty: true
    networks:
      - node-network  
    depends_on:
      - nodejs    

networks:
  node-network:
    driver: bridge    